### ISSUE TITLE
multiple images call multiple script tags

### ISSUE THREAD

**Issue by jemont** [cdowdy/boltresponsiveimages#17]
when i have multiple images, like in a blog list where I show 6 blog post with images, the addAsset method is called 6 times. for now i commentent out 

`$app['asset.queue.snippet']->add($asset);`

and included the asset once in my template

**Comment by cdowdy** [comment]
well rats! I thought I fixed that!   

What version are you on? 

related #13

**Comment by jemont** [comment]
ok sorry i was on 2.0.4. Just updated and yeah you fixed it. I discovered the issue a few weeks ago,  but never posted it here. sorry agin

**Comment by cdowdy** [comment]
@jemont o no worries! I thought I messed up the newest release haha. I appreciate you posting an issue about it though!
